# Jekyll settings
markdown: redcarpet
redcarpet:
  extensions: ['tables', 'autolink', 'no_intra_emphasis']
pygments: true
permalink: /posts/:title
exclude: ['sass', 'vendor', 'Gemfile', 'Gemfile.lock']
auto: true
pagenate: 1

# Site information
title: NIL
name: Tomohiro TAIRA
url: http://tomohiro.me
twitter: Tomohiro
github: Tomohiro
gravatar_url: https://gravatar.com/avatar/b26ba8ab9e0d6e3f92cbc7f8e320fc11
