# Site information
title: DEVELOPER IN THE SHELL
name: Tomohiro TAIRA
twitter: Tomohiro
gravatar_url: https://gravatar.com/avatar/b26ba8ab9e0d6e3f92cbc7f8e320fc11

# Jekyll settings
permalink: /posts/:title
exclude:
  - _scss
  - _coffee
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - robots.txt

# Plugins
#   Adding Jekyll plugins to a GitHub Pages site - User Documentation
#   https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-feed

# Jekyll Feed plugin configuration
# https://github.com/jekyll/jekyll-feed
feed:
  path: atom.xml
