# Site information
title: DEVELOPER IN THE SHELL
name: Tomohiro TAIRA
url: http://tomohiro.me
twitter: Tomohiro
github: Tomohiro
gravatar_url: https://gravatar.com/avatar/b26ba8ab9e0d6e3f92cbc7f8e320fc11

# Jekyll settings
permalink: /posts/:title
exclude: ['_scss', '_coffee', 'vendor', 'Gemfile', 'Gemfile.lock']
